(async function(){'use strict';const U=RBIUI,R=RBIRules,$=U.$;let data=null,selected=null,page=0,busy=false;
const esc=U.escape;
function cents(v){if(v==null||String(v).trim()==='')return null;if(!/^\d{1,7}(\.\d{1,2})?$/.test(String(v).trim()))throw new Error('Use a positive dollar amount with no more than two decimal places.');return Math.round(Number(v)*100);}
const dollars=n=>n==null?'':(n/100).toFixed(2);
function fields(form){const b=Object.fromEntries(new FormData(form));form.querySelectorAll('input[type=checkbox]').forEach(i=>b[i.name]=i.checked);return b;}
async function run(fn){if(busy)return;busy=true;U.setError($('#adminError'),'');U.setError($('#adminSuccess'),'');try{await fn();}catch(e){U.setError($('#adminError'),e.message);$('#adminError').scrollIntoView({block:'center'});}finally{busy=false;}}
function good(msg){$('#adminSuccess').textContent=msg;$('#adminSuccess').hidden=false;}
function currentBatch(){return data?.batches.find(b=>b.id===selected?.batch_id)||null;}
function renderList(){
 const orders=data.orders;$('#metrics').innerHTML=`<div class="box"><span class="small">Requests on this page</span><b>${orders.filter(r=>r.data.stage==='requested').length}</b></div><div class="box"><span class="small">Paid orders on this page</span><b>${orders.filter(r=>r.data.stage==='paid').length}</b></div><div class="box"><span class="small">Open cancellation requests</span><b>${orders.filter(r=>r.data.cancellation&&!['refunded','cancelled','declined'].includes(r.data.stage)).length}</b></div>`;
 $('#orderList').innerHTML=orders.length?orders.map(row=>`<button class="order-button ${selected?.id===row.id?'active':''}" data-order="${esc(row.id)}"><b>${esc(row.data.buyer.name)}</b><small>${esc(row.id)} · ${row.data.quantity} chips</small><span class="tag">${esc(R.stageLabels[R.effectiveStage(row.data,data.batches.find(b=>b.id===row.batch_id))])}</span>${row.data.cancellation?'<small class="danger-text">Cancellation requested</small>':''}</button>`).join(''):'<div class="empty">No requests on this page yet.</div>';
 $('#orderList').querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{selected=data.orders.find(o=>o.id===b.dataset.order);renderList();renderOrder();});
 $('#prevPage').disabled=page===0;$('#nextPage').disabled=!data.hasMore;$('#pageLabel').textContent=`Page ${page+1}. Showing up to 50 orders. Use “Find by order number” for older orders.`;
}
function checkbox(name,label){return `<label class="check"><input type="checkbox" name="${name}" required><span>${label}</span></label>`;}
function input(name,label,value='',type='text',required=true){return `<label class="field">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''}></label>`;}
function shippingForm(action='ship'){
 return `<form class="box action-form" data-action="${action}"><h3>${action==='ship'?'Ship this order':'Correct tracking details'}</h3><div class="form-grid"><label class="field">Carrier<select name="carrier">${['USPS','UPS','FedEx','DHL'].map(x=>`<option ${selected.data.shipment?.carrier===x?'selected':''}>${x}</option>`).join('')}</select></label>${input('trackingNumber','Tracking number',selected.data.shipment?.number||'')}</div>${action==='ship'?checkbox('handedToCarrier','The package was handed to the carrier. This is not just a printed label.'):''}<button class="btn primary mt16">${action==='ship'?'Mark shipped + add tracking':'Update tracking'}</button></form>`;
}
function renderOrder(){
 if(!selected)return;const d=selected.data,b=currentBatch(),q=d.quote,pricing=R.price(d.items),closed=['cancelled','refunded','declined'].includes(d.stage);
 let content=`<div class="box"><span class="eyebrow">${esc(selected.id)}</span><h2>${esc(d.buyer.name)}</h2><p>${esc(d.buyer.business||'Independent repair tech')}<br><a href="tel:${esc(d.buyer.phone.replace(/[^+\d]/g,''))}">${esc(d.buyer.phone)}</a></p><p class="small break">${esc(d.buyer.page||'No repair page supplied')}<br>Postal code: ${esc(d.buyer.postal)}<br>Batch: ${esc(b?.label||'Unknown')}</p><p class="small break"><b>Buyer notes:</b> ${esc(d.buyer.notes||'None')}</p><span class="pill">${esc(R.stageLabels[R.effectiveStage(d,b)])}</span>${d.items.map(i=>`<div class="line"><span>${esc(R.byId[i.id].label)}</span><b>× ${i.qty}</b></div>`).join('')}${d.shippingAddress?`<details class="mt16"><summary>Private shipping address</summary><p class="break">${esc(d.shippingAddress)}</p></details>`:''}${d.payment?`<p class="small mt16"><b>Payment:</b> ${R.money(d.payment.amountCents)} · ${esc(d.payment.method)}<br>Reference: ${esc(d.payment.reference)}</p>`:''}<div class="actions"><button class="btn" id="resetBuyerLink">Make a new private link</button>${q?'<button class="btn" id="copyQuoteMessage">Copy quote message</button>':''}</div><div id="newBuyerLink"></div></div>`;
 if(d.cancellation&&!closed)content+=`<div class="notice"><b>Cancellation request is open.</b><br>${esc(d.cancellation.reason)}<br>Do not ship until it is resolved. A paid cancellation needs the appropriate refund, not a silent status change.</div><form class="box action-form" data-action="resolve_cancel"><h3>Buyer decided to continue?</h3><label class="field">Record the agreement<textarea name="message" required maxlength="1000"></textarea></label>${checkbox('buyerAgreed','The buyer explicitly agreed to continue. I am not clearing this without their agreement.')}<button class="btn mt16">Record agreement</button></form>`;
 if(['requested','approved'].includes(d.stage)){
 content+=`<form class="box action-form" data-action="approve"><h3>${q?'Revise the quote':'1. Check it, then approve'}</h3><p class="small">Changing the quote resets buyer acceptance. Do not ask for payment until they accept the new quote.</p><div class="form-grid">${pricing.bulk?input('unitPrice','Approved bulk price per chip ($)',dollars(q?.unitCents),'text'):`<div class="field">Chips subtotal<p>${R.money(pricing.subtotalCents)} at ${R.money(pricing.unitCents)} each</p></div>`}${input('shipping','Shipping ($)',dollars(q?.shippingCents))}${input('tax','Tax ($)',dollars(q?.taxCents))}${input('shipBy','Estimated shipment from Rich by',q?.shipBy||'','date')}<label class="field full">Verified delivery address<textarea name="shippingAddress" required maxlength="600">${esc(d.shippingAddress||'')}</textarea></label><label class="field full">Compatibility details the buyer will see<textarea name="compatibilityNotes" required maxlength="1800" placeholder="Exact supported model/region, carrier/software conditions, what was checked, and any limits.">${esc(q?.compatibilityNotes||'')}</textarea></label></div>${checkbox('compatibilityChecked','I verified the exact chip and compatibility conditions for every selected model.')}${checkbox('guidesChecked','I opened and checked the matching supplier instructions. I am not using the 12 / 12 Pro demo for these models.')}${checkbox('authorizedDevices','The buyer confirmed authorized service work on the relevant devices.')}<button class="btn primary mt24">${q?'Save revised quote':'Approve + publish full quote'}</button><p class="fine">Blank shipping or tax is not treated as zero. Enter 0 explicitly when appropriate.</p></form>`;
 }
 if(d.stage==='approved'){
 content+=`<div class="box"><h3>2. Verify the actual payment</h3><p class="small">Quote total: <b>${R.money(q.totalCents)}</b><br>${q.acceptedAt?'Buyer accepted on '+U.formatDate(q.acceptedAt):'Buyer has not accepted this quote yet.'}</p>${q.acceptedAt?`<form class="action-form" data-action="paid"><div class="form-grid">${input('amount','Amount actually received ($)',dollars(q.totalCents))}<label class="field">Payment method<select name="method"><option>Cash App</option><option>Zelle</option><option>Other</option></select></label>${input('reference','Transaction reference')}</div>${checkbox('paymentVerified','I checked the actual payment in my account. This is not based only on a screenshot.')}<button class="btn primary mt24">Record payment + open buyer pack</button></form>`:'<p class="notice">Ask the buyer to review and accept the quote on their private order page first.</p>'}</div>`;
 }
 if(d.stage==='paid')content+=b?.stage==='arrived'?shippingForm('ship'):'<div class="box"><h3>3. Wait for the batch</h3><p class="small">The buyer pack is open. Use “Batch updates” once for everyone. You can add the outbound tracking number after this batch arrives at Rich.</p></div>';
 if(d.stage==='shipped'){content+=shippingForm('tracking');content+=`<form class="box action-form" data-action="deliver"><h3>Delivered?</h3>${checkbox('deliveryVerified','I confirmed delivery in the carrier tracking record.')}<button class="btn primary mt16">Mark delivered</button></form>`;}
 if(!closed){content+=`<form class="box action-form" data-action="note"><h3>Post an order update</h3><label class="field">This message is visible to the buyer<textarea name="message" required maxlength="1000" placeholder="Say what happened and what happens next."></textarea></label><button class="btn mt16">Post update</button></form>`;}
 if(['requested','approved'].includes(d.stage))content+=`<form class="box action-form" data-action="cancel"><h3>Close an unpaid request</h3><label class="field">Reason the buyer will see<textarea name="message" required maxlength="800"></textarea></label><button class="btn danger mt16">Cancel unpaid request</button></form>`;
 if(['paid','shipped','delivered'].includes(d.stage))content+=`<details class="mb0"><summary>Record a full refund</summary><form class="action-form mt16" data-action="refund"><p class="small">This site cannot send the refund. Issue it through the original payment method first.</p><div class="form-grid">${input('amount','Refund actually issued ($)',dollars(d.payment.amountCents))}${input('reference','Refund transaction reference')}</div>${checkbox('refundVerified','I issued and verified this full refund. I understand private buyer-pack access will close.')}<button class="btn danger mt16">Record verified full refund</button></form></details>`;
 $('#orderDetail').innerHTML=content;
 $('#orderDetail').querySelectorAll('.action-form').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;run(async()=>{const payload=fields(form);payload.action=form.dataset.action;if('shipping'in payload)payload.shippingCents=cents(payload.shipping);if('tax'in payload)payload.taxCents=cents(payload.tax);if('unitPrice'in payload)payload.unitCents=cents(payload.unitPrice);if('amount'in payload)payload.amountCents=cents(payload.amount);const r=await U.api('admin/order-action',{...payload,id:selected.id,revision:selected.revision});selected=r.order;await load(selected.id);good('Saved. The buyer sees the update on their private page.');});}));
 $('#resetBuyerLink').onclick=()=>{if(!confirm('Make a new private link? The old buyer link will stop working. Send the new one privately.'))return;run(async()=>{const r=await U.api('admin/order-action',{id:selected.id,revision:selected.revision,action:'renew_access'});selected=r.order;const link=U.orderLink(selected.id,r.key);$('#newBuyerLink').innerHTML=`<div class="notice green mt16">Old link is now invalid. Save and send this new link privately.</div><input class="private-link" readonly value="${esc(link)}" aria-label="New private buyer link"><button class="btn" id="copyNewLink">Copy new link</button>`;$('#copyNewLink').onclick=e=>U.copy(link,e.currentTarget);});};
 $('#copyQuoteMessage')?.addEventListener('click',e=>U.copy(`Hi ${d.buyer.name}, your ${selected.id} quote is ready.\n${d.quantity} chips: ${R.money(q.subtotalCents)}\nShipping: ${R.money(q.shippingCents)}\nTax: ${R.money(q.taxCents)}\nFull total: ${R.money(q.totalCents)}\nEstimated shipment from Rich by: ${U.formatDate(q.shipBy)}. Carrier transit is additional.\nPlease open your saved private order link, read the compatibility notes and return policy, and accept the quote before sending payment. I will send payment instructions privately.`,e.currentTarget));
}
function renderSetup(){
 $('#launchMissing').innerHTML=data.missing.length?'<ul>'+data.missing.map(m=>'<li>'+esc(m)+'</li>').join('')+'</ul>':'<p class="success-text">Launch settings are filled in. Run the live smoke test in START-HERE.md before advertising.</p>';
 const f=$('#setupForm');for(const [key,val]of Object.entries(data.settings)){if(!f.elements[key])continue;if(f.elements[key].type==='checkbox')f.elements[key].checked=val===true;else f.elements[key].value=val||'';}
 const selectedValue=$('#batchSelect').value;$('#batchSelect').innerHTML='<option value="">New batch</option>'+data.batches.map(b=>`<option value="${esc(b.id)}">${esc(b.label)}${b.is_open?' (open)':''}</option>`).join('');if(data.batches.some(b=>b.id===selectedValue))$('#batchSelect').value=selectedValue;
}
async function load(keepId){
 data=U.preview&&window.RBI_PREVIEW_ADMIN?window.RBI_PREVIEW_ADMIN:await U.api('admin/overview?page='+page);
 $('#loginForm').hidden=true;$('#dashboard').hidden=false;$('#signedIn').textContent=U.preview?'OWNER PREVIEW — NO LIVE DATA':'SIGNED IN · '+(data.user?.email||'OWNER');
 if(keepId){selected=data.orders.find(r=>r.id===keepId)||selected;}
 renderList();renderSetup();if(selected)renderOrder();
}
function fillBatch(){const b=data.batches.find(b=>b.id===$('#batchSelect').value),f=$('#batchForm');f.reset();if(b){for(const [k,v]of Object.entries(b)){if(!f.elements[k])continue;if(f.elements[k].type==='checkbox')f.elements[k].checked=v===true;else f.elements[k].value=v??'';}}$('#manifest').hidden=true;}
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();run(async()=>{await U.api('login',{email:$('#adminEmail').value,password:$('#adminPassword').value});$('#adminPassword').value='';await load();});});
$('#logoutButton').onclick=()=>run(async()=>{await U.api('logout',{});data=null;selected=null;$('#dashboard').hidden=true;$('#loginForm').hidden=false;$('#orderDetail').innerHTML='';});
$('.admin-tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>{$('.admin-tabs').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));['orders','batches','setup'].forEach(t=>$('#'+t+'Panel').hidden=t!==b.dataset.tab);});
$('#refreshAdmin').onclick=()=>run(()=>load(selected?.id));$('#nextPage').onclick=()=>run(async()=>{page++;selected=null;await load();});$('#prevPage').onclick=()=>run(async()=>{page=Math.max(0,page-1);selected=null;await load();});
$('#findOrderForm').onsubmit=e=>{e.preventDefault();run(async()=>{const id=$('#findOrderId').value.trim().toUpperCase();if(U.preview){selected=data.orders.find(r=>r.id===id);if(!selected)throw new Error('Only sample orders exist in this preview.');}else selected=(await U.api('admin/order?id='+encodeURIComponent(id))).order;renderList();renderOrder();});};
$('#setupForm').onsubmit=e=>{e.preventDefault();run(async()=>{await U.api('admin/settings',fields(e.target));await load(selected?.id);good('Setup saved.');});};
$('#batchSelect').onchange=fillBatch;$('#batchStage').onchange=()=>{if($('#batchStage').value!=='collecting')$('#batchForm').elements.is_open.checked=false;};
$('#batchForm').onsubmit=e=>{e.preventDefault();run(async()=>{const b=data.batches.find(b=>b.id===$('#batchSelect').value);const result=await U.api('admin/batch',{...fields(e.target),id:b?.id||null,revision:b?.revision});await load(selected?.id);$('#batchSelect').value=result.batch.id;fillBatch();good('Batch saved. Linked paid orders now use this update.');});};
$('#loadManifest').onclick=()=>run(async()=>{const id=$('#batchSelect').value;if(!id)throw new Error('Choose a saved batch first.');const r=await U.api('admin/batch-summary?id='+encodeURIComponent(id));const block=(m,title)=>`<h3>${title}</h3><p class="small">${m.orderCount} paid orders · ${m.quantity} chips</p>${m.items.filter(i=>i.qty).map(i=>`<div class="line"><span>${esc(i.label||R.byId[i.id]?.label||i.id)}</span><b>${i.qty}</b></div>`).join('')}`;$('#manifest').innerHTML=block(r.current,'Currently paid and not refunded')+(r.ordered?'<div class="divider">'+block(r.ordered,'Snapshot when supplier order was placed')+'</div>':'<p class="notice mt16">Your reported supplier minimum is 40 pieces. These totals exclude unpaid requests. Confirm how any shortfall will be funded before placing the supplier order.</p>')+'<button class="btn mt16" id="copyManifest">Copy paid model totals</button>';$('#manifest').hidden=false;$('#copyManifest').onclick=e=>U.copy(`PAID MODEL TOTALS\n${r.current.items.map(i=>i.label+': '+i.qty).join('\n')}\nTotal chips: ${r.current.quantity}\nPaid orders: ${r.current.orderCount}\nSaved: ${r.current.savedAt}`,e.currentTarget);});
$('#addMessageOrder').onclick=()=>{
 const box=$('#manualOrder');box.hidden=!box.hidden;if(box.hidden)return;
 box.innerHTML=`<form class="form-card mt24" id="manualOrderForm"><h3>Add a buyer who messaged you</h3><p class="small">This creates an unpaid request. It does not approve the buyer or mark a payment.</p><div class="form-grid">${input('name','Buyer name')}${input('phone','Phone number','','tel')}<label class="field">Buyer type<select name="buyerType"><option value="independent">Independent repair tech</option><option value="shop">Repair shop</option></select></label>${input('business','Shop / repair name','','text',false)}${input('postal','Postal code')}${input('page','Repair page','','text',false)}${R.products.map(p=>input(p.id,esc(p.short)+' quantity','0','number')).join('')}</div>${checkbox('consent','The buyer confirmed repair experience, the preorder terms, and permission to contact them about this request. I am entering their request with permission.')}<button class="btn primary mt24">Save unpaid request</button></form>`;
 let keys={accessKey:U.secureKey(),requestKey:crypto.randomUUID()};
 $('#manualOrderForm').onsubmit=e=>{e.preventDefault();run(async()=>{const b=fields(e.target);const out=await U.api('admin/orders',{...b,...keys,items:R.products.map(p=>({id:p.id,qty:Number(b[p.id])})),experienced:b.consent===true,preorder:b.consent===true,contactConsent:b.consent===true,notes:'Entered by Rich from a buyer message with permission.'});const link=U.orderLink(out.id,keys.accessKey);await load();box.innerHTML=`<div class="receipt"><h3>Unpaid request saved.</h3><p>Send this link privately to the buyer.</p><input class="private-link" readonly value="${esc(link)}"><button class="btn" id="copyManualLink">Copy buyer link</button></div>`;$('#copyManualLink').onclick=e=>U.copy(link,e.currentTarget);});};
};
try{await load();}catch{if(U.preview)U.setError($('#adminError'),'Owner preview is not connected to a live account.');}
})();
