(async function(){'use strict';const U=RBIUI,R=RBIRules,$=U.$;let access=U.readAccess(),order=null,busy=false,conf=await U.config();
function quoteHTML(q){if(!q)return '<p class="small">Rich is reviewing your request. Do not send payment yet.</p>';
 return `<div class="line"><span>Chips</span><b>${R.money(q.subtotalCents)}</b></div><div class="line"><span>Shipping</span><b>${R.money(q.shippingCents)}</b></div><div class="line"><span>Tax</span><b>${R.money(q.taxCents)}</b></div><div class="line total"><span>Full price</span><b>${R.money(q.totalCents)}</b></div><p class="small">Estimated shipment from Rich by <b>${U.formatDate(q.shipBy)}</b>.<br>Quote valid through ${U.formatDate(q.expiresOn)}. Carrier transit follows shipment.</p><h3 class="mt24">Compatibility notes</h3><p class="small break">${U.escape(q.compatibilityNotes)}</p><details><summary>Your quoted return / defect policy</summary><p class="break">${U.escape(q.returnsPolicy)}</p></details>${order.baseStage==='approved'?(q.acceptedAt?`<div class="notice green mt16">Quote accepted ${U.formatDate(q.acceptedAt)}. Message Rich for your private payment instructions.</div>`:`<label class="check"><input type="checkbox" id="acceptCheck"><span>I have read this quote, its date, compatibility notes, and return policy. I understand the full total.</span></label><button class="btn primary wide mt16" id="acceptQuote">Accept this quote</button>`):''}`;
}
function render(){
 $('#lookupForm').hidden=true;$('#orderView').hidden=false;
 const stages=['requested','approved','paid','ordered','inbound','arrived','shipped','delivered'],pos=stages.indexOf(order.stage),closed=['cancelled','refunded','declined'].includes(order.stage);
 const link=access?U.orderLink(access.id,access.key):'';
 const ship=order.shipment,track=ship?R.trackingURL(ship.carrier,ship.number):null;
 $('#orderView').innerHTML=`${U.preview?'<div class="notice">SAMPLE ORDER · This status and all example dates are for design review only.</div>':''}<div class="page-grid"><div><section class="box"><span class="eyebrow">${U.escape(order.id)}</span><h2>${U.escape(R.stageLabels[order.stage]||order.stage)}</h2><p class="small">Order updated: ${U.formatDate(order.updatedAt)}. ${order.batch?'Batch updated: '+U.formatDate(order.batch.updatedAt)+'.':''}</p>${closed?'':`<ol class="timeline">${stages.map((s,i)=>`<li class="${i===pos?'current':i<pos?'done':''}" ${i===pos?'aria-current="step"':''}>${U.escape(R.stageLabels[s])}</li>`).join('')}</ol>`}${order.cancellation?'<div class="notice">Your cancellation request is recorded. Rich will confirm the next steps. Recording a request does not itself issue a refund.</div>':''}${order.refund?`<div class="notice green">Refund recorded: ${R.money(order.refund.amountCents)} on ${U.formatDate(order.refund.recordedAt)}. Confirm receipt in your payment app.</div>`:''}<div class="actions"><button class="btn" id="refreshOrder">Refresh status</button>${access?'<button class="btn ghost" id="copyOrderLink">Copy my private link</button>':''}</div></section>
 ${order.batch?`<section class="box"><span class="eyebrow">YOUR SUPPLIER BATCH</span><h3>${U.escape(order.batch.label)}</h3><p class="small">Supplier order ${order.batch.orderedOn?'placed: '+U.formatDate(order.batch.orderedOn):'planned by: '+U.formatDate(order.batch.orderBy)}<br>Next update: ${U.formatDate(order.batch.nextUpdateOn)}</p>${order.batch.expectedStart&&order.batch.expectedEnd?`<p class="small">Estimated arrival at Rich: ${U.formatDate(order.batch.expectedStart)} – ${U.formatDate(order.batch.expectedEnd)}. This is not your delivery date.</p>`:''}<p class="break">${U.escape(order.batch.note||'Rich has not posted a new batch note yet.')}</p></section>`:''}
 <section class="box"><h3>Your shipment</h3>${track?`<p><b>${U.escape(ship.carrier)}</b><br><span class="break">${U.escape(ship.number)}</span></p><a class="btn primary" href="${U.escape(track)}" target="_blank" rel="noopener noreferrer">Track my package ↗</a><p class="fine">Carrier updates are on the carrier's page. This site does not automatically poll delivery scans.</p>`:'<p class="small">Your tracking number appears here after Rich hands your package to the carrier. There is no outbound tracking number yet.</p>'}</section>
 <section class="box"><h3>Your updates</h3><ul class="history">${(order.events||[]).slice().reverse().map(e=>`<li><time>${U.formatDate(e.at)}</time>${U.escape(e.message)}</li>`).join('')}</ul></section></div>
 <aside><section class="box"><h3>Your chip mix</h3>${order.items.map(i=>`<div class="line"><span>${U.escape(R.byId[i.id]?.short||i.id)}</span><b>× ${i.qty}</b></div>`).join('')}<div class="line"><span>Total chips</span><b>${order.quantity}</b></div><h3 class="mt24">${order.quote?'Your approved quote':'Awaiting review'}</h3>${quoteHTML(order.quote)}</section>
 <section class="box"><span class="eyebrow">YOUR BUYER BONUS</span><h3>${order.bonusAvailable?'Your pack is open.':'Opens after payment.'}</h3><p class="small">Your AI character prompts, 15-second video prompts, message scripts, and private Telegram access.</p>${order.bonusAvailable?'<a class="btn primary wide" href="buyer-bonus-pack.html">Open my buyer pack ↗</a>':'<p class="tag">Waiting for verified payment</p>'}</section>
 <section class="box"><h3>Questions or a cancellation?</h3>${conf.supportURL?`<a class="btn wide" target="_blank" rel="noopener noreferrer" href="${U.escape(conf.supportURL)}">Message Rich ↗</a>`:'<p class="small">Contact Rich using the same conversation you used for your preorder.</p>'}${!closed&&!order.cancellation?'<details class="mt16"><summary>Request cancellation</summary><label class="field mt16">Tell Rich what happened<textarea id="cancelReason" maxlength="600" placeholder="Your reason"></textarea></label><button class="btn danger wide mt16" id="requestCancel">Send cancellation request</button></details>':''}<p class="fine">Keep your access key private. No card, banking, or phone passwords are needed here.</p></section></aside></div>`;
 $('#refreshOrder').onclick=load;$('#copyOrderLink')?.addEventListener('click',e=>U.copy(link,e.currentTarget));
 $('#acceptQuote')?.addEventListener('click',()=>action({action:'accept_quote',quoteVersion:order.quote.version,confirm:$('#acceptCheck').checked}));
 $('#requestCancel')?.addEventListener('click',()=>{const reason=$('#cancelReason').value.trim();if(!reason){U.setError($('#trackError'),'Tell Rich why you are requesting cancellation.');return;}if(confirm('Send this cancellation request to Rich? This does not automatically issue a refund.'))action({action:'cancel',reason});});
}
async function action(body){if(busy)return;busy=true;U.setError($('#trackError'),'');try{const r=await U.api('buyer-action',{...access,...body});order=r.order;render();}catch(e){U.setError($('#trackError'),e.message);}finally{busy=false;}}
async function load(){if(U.preview&&window.RBI_PREVIEW_ORDER){order=window.RBI_PREVIEW_ORDER;render();return;}if(!access)return;U.setError($('#trackError'),'');try{const r=await U.api('lookup',access);order=r.order;U.setAccess(access);render();}catch(e){U.setError($('#trackError'),e.message);$('#lookupForm').hidden=false;$('#orderView').hidden=true;}}
$('#lookupForm').addEventListener('submit',e=>{e.preventDefault();access={id:$('#lookupId').value.trim().toUpperCase(),key:$('#lookupKey').value.trim()};load();});
if(access){$('#lookupId').value=access.id;$('#lookupKey').value=access.key;}await load();
})();
